name: Generate preview images
on:
  workflow_dispatch:

jobs:
  target_list:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.matrix.outputs.value }}
    steps:
      - id: matrix
        #  echo "value=[\"80s-neon\", \"abate\", \"abecedarium\", \"absolutegruv\", \"abyssal\", \"adrenaline\", \"adwaita\", \"agate\", \"al-dente\", \"allium\", \"anuppuccin\", \"apatheia\", \"apex\", \"arcane\", \"atom\", \"atomus\", \"aura-dark\", \"aura\", \"aurora-twilight\", \"aurora\", \"autotape\", \"ayu-light-mirage\", \"ayu-mirage\", \"base2tone\", \"behave-dark\", \"big-bold\", \"black\", \"blackbird\", \"blossom\", \"blue-topaz\", \"bolt\", \"border\", \"bossidian\", \"brainhack\", \"brutalism\", \"buena-vista\", \"carbon\", \"cardstock\", \"catppuccin\", \"celestial-night\", \"charcoal\", \"chiaroscuroflow\", \"christmas\", \"cobalt-peacock\", \"colored-candy\", \"comfort-color-dark\", \"comfort-dark\", \"comfort-smooth\", \"comfort\", \"covert\", \"creature\", \"creme-brulee\", \"cyber-glow\", \"cybertron-shifted\", \"cybertron\", \"dark-castle\", \"dark-clarity\", \"dark-graphite-pie\", \"dark-graphite\", \"dark-moss\", \"darkember\", \"darkyan\", \"dawn\", \"dayspring\", \"deeper-work\", \"default\", \"dekurai\", \"discordian\", \"dracula-for-obsidian\", \"dracula-gemini\", \"dracula-lyt\", \"dracula-official\", \"dracula-plus\", \"dracula-slim\", \"dune\", \"dunite\", \"dynamic-color\", \"ebullientworks\", \"eldritch\", \"elegance\", \"encore\", \"ethereon\", \"everblush\", \"everforest-enchanted\", \"everforest\", \"evergreen-shadow\", \"evilred\", \"faded\", \"feather\", \"firefly\", \"flexoki\", \"focus\", \"fusion\", \"garden-gnome-adwaita-gtk\", \"gdct-dark\", \"gdct\", \"github-theme\", \"githubdhc\", \"gitsidian\", \"golden-topaz\", \"green-nightmare\", \"gummy-revived\", \"halcyon\", \"heboric\", \"hipstersmoothie\", \"hulk\", \"ia-writer\", \"ib-writer\", \"iceberg\", \"improved-potato\", \"ion\", \"its-theme\", \"jotter\", \"kakano\", \"kanagawa\", \"kiwi-mono\", \"kurokula\", \"latex\", \"lavender-mist\", \"lemons-theme\", \"light-bright\", \"listive\", \"lorens\", \"lumines\", \"lyt-mode\", \"mado-11\", \"mado-miniflow\", \"magicuser\", \"mammoth\", \"maple\", \"material-flat\", \"material-gruvbox\", \"material-ocean\", \"micro-mike\", \"midnight-fjord\", \"midnight\", \"minimal-edge\", \"minimal-resources\", \"minimal\", \"mint-breeze\", \"mistymauve\", \"mono-black-monochrome-charcoal\", \"monochroyou\", \"monokai\", \"moonlight\", \"muted-blue\", \"nebula\", \"neo\", \"neon-synthwave\", \"neovim\", \"neuborder\", \"nier\", \"nightfox\", \"nightingale\", \"nobb\", \"nordic\", \"northern-sky\", \"notation-2\", \"notation\", \"notswift\", \"novadust\"]" >> $GITHUB_OUTPUT
        run: |
          echo "value=[\"80s-neon\"]" >> $GITHUB_OUTPUT
      - run: |
          echo "${{ steps.matrix.outputs.value }}"
  generate_preview:
    needs: [target_list]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        value: ${{fromJSON(needs.target_list.outputs.matrix)}}
        color-scheme: [light, dark]
    steps:
      - name: Setup Directory
        run: mkdir runner_content
      - name: Clone Quartz Themes
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          path: runner_content/quartz-themes
      - name: Clone Quartz
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          repository: "jackyzha0/quartz"
          path: runner_content/quartz
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Setup Quartz Themes
        working-directory: ./runner_content/quartz-themes
        run: npm install
      - name: Set Theme
        working-directory: ./runner_content/quartz-themes
        run: npm run theme ${{ matrix.value }}
      - name: Setup Quartz
        working-directory: ./runner_content/quartz
        run: npm install
      - name: Build Quartz
        working-directory: ./runner_content/quartz
        run: npx quartz build -d docs
      - name: Set light/dark mode
        working-directory: ./runner_content/quartz/public
        run: sed -ir 's/<html/<html saved-theme="${{matrix.color-scheme}}"/' index.html
      - name: Generate preview image
        uses: saberzero1/github-actions-screenshot@main
        with:
          url: "file://${{github.workspace}}/runner_content/quartz/public/index.html"
          output: "previews/${{matrix.value}}-${{matrix.color-scheme}}.png"
          viewportWidth: 1920
          viewportHeight: 1080
          waitForTimeout: 2500
          theme: "${{matrix.color-scheme}}"
      - name: Upload image
        uses: actions/upload-artifact@v4
        with:
          name: ${{matrix.value}}-${{matrix.color-scheme}}
          path: "${{github.workspace}}/previews/*.png"
          overwrite: true
